directwrite: Honor global ClearType setting
alacritty/crossfont pull request #22
Opened 2020-12-29 01:50 UTC by r-c-f

This only uses the DWRITE_TEXTURE_CLEARTYPE_3x1 texture type if
ClearType itself is enabled elsewhere on Windows, and configures the
rendering options accordingly. The winuser feature is enabled in winapi
to allow for the checks.

2020-12-29 04:49 UTC, chrisduerr requested changes

2020-12-29 04:49 UTC, chrisduerr commented on src/directwrite/mod.rs
> +        }
Why do we have to check twice here if font smoothing should be enabled or not? That seems rather strange.

2020-12-29 04:49 UTC, chrisduerr commented on src/directwrite/mod.rs
> +            _ => panic!("invalid texture type"),
We shouldn't panic, instead the typesystem should be used to enforce that only the variants we want can be provided. One option would be an enum for example, or just a boolean really.

2020-12-29 06:58 UTC, r-c-f commented
Looking into doing this a bit more properly, the double-check would make sense if the rendering mode were selectable between standard anti-aliasing and ClearType proper, but using proper enums exposes the fact that ClearType is not selectable -- DWRITE_RENDERING_MODE_NATURAL and DWRITE_RENDERING_MODE_CLEARTYPE_NATURAL both evaluate to 4. As such I've reworded the commit to reflect what it's actually doing. 

Whether this is actually useful when done the right way is another matter, of course; the quality of rendering elsewhere suffers so dramatically with all anti-aliasing disabled that alacritty (using an outline approximation of a bitmap font, as DirectWrite doesn't support strikes in non-Asian typefaces) becomes in effect the one application I *don't* want using the system settings, leaving a local fork making it configurable the only sensible choice regardless of where this goes.

2020-12-29 07:32 UTC, chrisduerr commented
> Whether this is actually useful when done the right way is another matter, of course; the quality of rendering elsewhere suffers so dramatically with all anti-aliasing disabled that alacritty (using an outline approximation of a bitmap font, as DirectWrite doesn't support strikes in non-Asian typefaces) becomes in effect the one application I don't want using the system settings, leaving a local fork making it configurable the only sensible choice regardless of where this goes.

If this doesn't actually provide any benefit to you and no other user needs it, then it's probably best to not add any additional complexity that doesn't serve any purpose.

I'm curious if you've tried just always using `DWRITE_RENDERING_MODE_DEFAULT`? How does that behave, does it actually use the global setting or does it always use aliasing/noaliasing?

2020-12-31 08:41 UTC, r-c-f commented
I did try this initially, but it seems intended only as a placeholder (using it for rasterization yields yet another 80070057 error). Microsoft themselves seem to have acknowledged the deficiency here in the newer [`IDWriteFactory2::CreateGlyphRunAnalysis`](https://docs.microsoft.com/en-us/windows/win32/api/dwrite_2/nf-dwrite_2-idwritefactory2-createglyphrunanalysis) method with a parameter to set the antialiasing mode, but given a question of immediate usefulness and what would be prerequisite work in dwrote it's probably best to forget this indeed for the time being.

2020-12-31 08:41 UTC, closed without merging