Bump Size precision to 3 fp digits
alacritty/crossfont pull request #57
Opened 2023-12-03 02:31 UTC by kchibisov

--

There're likely better ways to do that, but it really sucks to deal with those sizes on hidpi, since you can't pick some of them.

We also can't use `f32` directly, since it's not `Hash`, so we could only do thins like that with fractions, etc.

2023-12-03 06:17 UTC, kchibisov commented
You can see example here https://github.com/alacritty/alacritty/pull/7410

2023-12-04 20:27 UTC, chrisduerr requested changes

2023-12-04 20:27 UTC, chrisduerr commented on src/darwin/mod.rs
> +        let scaled_size = Size::new(size.as_pt());
Name is wrong, right? It's just size or ponit size, not scaled size now?

This is also wrong a couple more times in this file, might be worth a quick grep for `scale`.

2023-12-04 20:27 UTC, chrisduerr commented on src/ft/mod.rs
> +        let size = f64::from(size.as_pt() * 96. / 72.);
Isn't this just `as_px`?

2023-12-04 22:09 UTC, chrisduerr approved these changes

2023-12-04 23:48 UTC, merged